In [1]:
import torch

In [2]:
a = torch.zeros(5)

print('a =', a)

a = tensor([0., 0., 0., 0., 0.])


In [3]:
print('a.size()=', a.size())

a.size()= torch.Size([5])


In [4]:
b = torch.zeros([2,3])

In [5]:
c = torch.zeros([3,2,4])
c

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [6]:
i = torch.rand(3)

In [7]:
i

tensor([0.9750, 0.4231, 0.1902])

In [8]:
j = torch.rand([2,3])
j

tensor([[0.5010, 0.7179, 0.4748],
        [0.5297, 0.0958, 0.4390]])

In [9]:
k=torch.randn(3)

In [10]:
k

tensor([ 0.4965,  2.0207, -1.8067])

In [11]:
l = torch.randn([2,3])
l

tensor([[-0.5614,  1.4817, -1.0582],
        [ 0.2533, -0.9575, -0.0862]])

In [12]:
n = torch.rand_like(k)
n

tensor([0.1225, 0.1610, 0.6873])

In [13]:
m = torch.rand_like(l)
m

tensor([[0.8448, 0.4080, 0.6155],
        [0.8178, 0.0513, 0.3595]])

In [15]:
o = torch.arange(start=1, end=11, step=2)

In [16]:
o

tensor([1, 3, 5, 7, 9])

In [17]:
o = torch.arange(1,11,2)

In [18]:
o

tensor([1, 3, 5, 7, 9])

In [19]:
p = torch.arange(1, 50, 0.7)

In [20]:
p

tensor([ 1.0000,  1.7000,  2.4000,  3.1000,  3.8000,  4.5000,  5.2000,  5.9000,
         6.6000,  7.3000,  8.0000,  8.7000,  9.4000, 10.1000, 10.8000, 11.5000,
        12.2000, 12.9000, 13.6000, 14.3000, 15.0000, 15.7000, 16.4000, 17.1000,
        17.8000, 18.5000, 19.2000, 19.9000, 20.6000, 21.3000, 22.0000, 22.7000,
        23.4000, 24.1000, 24.8000, 25.5000, 26.2000, 26.9000, 27.6000, 28.3000,
        29.0000, 29.7000, 30.4000, 31.1000, 31.8000, 32.5000, 33.2000, 33.9000,
        34.6000, 35.3000, 36.0000, 36.7000, 37.4000, 38.1000, 38.8000, 39.5000,
        40.2000, 40.9000, 41.6000, 42.3000, 43.0000, 43.7000, 44.4000, 45.1000,
        45.8000, 46.5000, 47.2000, 47.9000, 48.6000, 49.3000])

In [21]:
q = torch.empty(3)
q

tensor([-6.8364e-13,  4.3622e-41, -6.8364e-13])

In [26]:
p = torch.fill_(q,50)

In [27]:
p

tensor([50., 50., 50.])

In [28]:
li= [2,3,5314,2]

In [29]:
t = torch.tensor(li)

In [30]:
t

tensor([   2,    3, 5314,    2])

In [33]:
import numpy as np
u = np.array([[1,3,4]
             ,[2,3,5]])

In [34]:
v = torch.from_numpy(u)

In [35]:
v

tensor([[1, 3, 4],
        [2, 3, 5]])

In [36]:
p = v.float()

In [37]:
p

tensor([[1., 3., 4.],
        [2., 3., 5.]])

In [38]:
x = torch.tensor([5,3,4,12,1])

In [39]:
y = x.clone()
y

tensor([ 5,  3,  4, 12,  1])

In [40]:
a = torch.tensor([1,2,3])

In [41]:
a.device

device(type='cpu')

In [42]:
torch.cuda.is_available()

False

In [44]:
torch.cuda.get_device_name(device=0)

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [46]:
c =torch.tensor([[0,1,2],[3,4,5]])
c.is_contiguous()

True

In [47]:
d = c[:,:2]
d.is_contiguous

<function Tensor.is_contiguous>

In [48]:
d

tensor([[0, 1],
        [3, 4]])

In [49]:
d.is_contiguous()

False

In [50]:
e = d.contiguous()
e.is_contiguous()

True

In [51]:
f = torch.arange(12)

In [52]:
g = f.view(4,-1)

In [53]:
g

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [54]:
h = f.view(3,2,-1)

In [55]:
h

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

In [56]:
i = torch.randn(3,3)
i

tensor([[-2.1288, -1.0844, -0.6768],
        [ 0.8193,  0.7795, -0.0668],
        [ 0.4333,  0.3051,  0.4540]])

In [57]:
j = torch.flatten(i)
j

tensor([-2.1288, -1.0844, -0.6768,  0.8193,  0.7795, -0.0668,  0.4333,  0.3051,
         0.4540])

In [58]:
q = torch.randn(3,3,3)
q

tensor([[[-0.6011,  0.2497,  0.7399],
         [-0.0526, -1.8308,  1.6127],
         [ 0.3554, -0.6475, -0.8198]],

        [[ 0.0784, -1.6973,  0.6670],
         [-0.5811, -0.7926,  0.4753],
         [-0.1741, -0.7766, -0.1511]],

        [[-0.7033, -0.0222, -0.5097],
         [ 0.4799,  1.5789, -1.2425],
         [-0.6660,  3.2967,  0.2306]]])

In [60]:
p = torch.flatten(q,1)
p

tensor([[-0.6011,  0.2497,  0.7399, -0.0526, -1.8308,  1.6127,  0.3554, -0.6475,
         -0.8198],
        [ 0.0784, -1.6973,  0.6670, -0.5811, -0.7926,  0.4753, -0.1741, -0.7766,
         -0.1511],
        [-0.7033, -0.0222, -0.5097,  0.4799,  1.5789, -1.2425, -0.6660,  3.2967,
          0.2306]])

In [61]:
k = torch.randn(3,2,2)
k

tensor([[[ 0.2853, -0.2508],
         [-0.5478, -0.6968]],

        [[-0.9104,  0.0816],
         [ 0.0468, -0.1741]],

        [[-0.9292, -1.6994],
         [-1.0762,  0.2969]]])

In [62]:
print(k.shape)

torch.Size([3, 2, 2])


In [63]:
l = torch.flatten(k, 0)

In [64]:
l

tensor([ 0.2853, -0.2508, -0.5478, -0.6968, -0.9104,  0.0816,  0.0468, -0.1741,
        -0.9292, -1.6994, -1.0762,  0.2969])

In [65]:
l = torch.flatten(k,1)
l

tensor([[ 0.2853, -0.2508, -0.5478, -0.6968],
        [-0.9104,  0.0816,  0.0468, -0.1741],
        [-0.9292, -1.6994, -1.0762,  0.2969]])

In [66]:
l = torch.flatten(k,2)
l

tensor([[[ 0.2853, -0.2508],
         [-0.5478, -0.6968]],

        [[-0.9104,  0.0816],
         [ 0.0468, -0.1741]],

        [[-0.9292, -1.6994],
         [-1.0762,  0.2969]]])

In [67]:
m = torch.flatten(k,0,1)
m

tensor([[ 0.2853, -0.2508],
        [-0.5478, -0.6968],
        [-0.9104,  0.0816],
        [ 0.0468, -0.1741],
        [-0.9292, -1.6994],
        [-1.0762,  0.2969]])

In [69]:
k.shape

torch.Size([3, 2, 2])

In [70]:
m.shape

torch.Size([6, 2])

In [71]:
l = torch.flatten(k,0,2)
l

tensor([ 0.2853, -0.2508, -0.5478, -0.6968, -0.9104,  0.0816,  0.0468, -0.1741,
        -0.9292, -1.6994, -1.0762,  0.2969])

In [72]:
l.shape

torch.Size([12])

In [73]:
n = torch.arange(12)

In [74]:
o = n.reshape(4,-1)
o

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [75]:
p = n.reshape(3,2,-1)
p

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

In [81]:
a = torch.tensor([[0,1,2], [3,4,5]])
re = a.transpose(0,1)
re

tensor([[0, 3],
        [1, 4],
        [2, 5]])

In [84]:
s = torch.tensor([[[0,1],[2,3],[4,5]],[[6,7],[8,9],[10,11]],[[12,13],[14,15],[16,17]]])
s

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]])

In [89]:
a = s.transpose(1,2)
a

tensor([[[ 0,  2,  4],
         [ 1,  3,  5]],

        [[ 6,  8, 10],
         [ 7,  9, 11]],

        [[12, 14, 16],
         [13, 15, 17]]])

In [87]:
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [90]:
u=torch.randn(1,3,4)
v=torch.squeeze(u)
v

tensor([[-0.2737,  1.7663, -0.6062,  1.3402],
        [ 0.5260, -0.0966, -0.5735,  0.9643],
        [ 0.7334,  0.5687,  0.7735, -0.6714]])

In [91]:
u

tensor([[[-0.2737,  1.7663, -0.6062,  1.3402],
         [ 0.5260, -0.0966, -0.5735,  0.9643],
         [ 0.7334,  0.5687,  0.7735, -0.6714]]])

In [92]:
v =torch.randn(1,1,4)
x = torch.squeeze(v)
x

tensor([-0.8732,  0.9702, -0.3487, -0.3101])

In [94]:
t = torch.squeeze(v,0)
t

tensor([[-0.8732,  0.9702, -0.3487, -0.3101]])

In [96]:
t= torch.squeeze(v,1)
t

tensor([[-0.8732,  0.9702, -0.3487, -0.3101]])

In [97]:
y = torch.randn(3,4)
z = torch.unsqueeze(y, dim=0)
z

tensor([[[ 0.7651,  0.1204, -1.2953, -0.5062],
         [-0.3788,  0.4929,  1.1877, -0.2837],
         [-0.9137, -0.9578,  0.6132,  0.2754]]])

In [98]:
z = torch.unsqueeze(y, dim=1)
z

tensor([[[ 0.7651,  0.1204, -1.2953, -0.5062]],

        [[-0.3788,  0.4929,  1.1877, -0.2837]],

        [[-0.9137, -0.9578,  0.6132,  0.2754]]])

In [99]:
z.shape

torch.Size([3, 1, 4])

In [100]:
z = torch.unsqueeze(y, dim=2)
z.shape

torch.Size([3, 4, 1])

In [102]:
red_channel=torch.tensor([[255,0],[0,255]])
green_channel=torch.tensor([[0,255],[0,255]])
blue_channel=torch.tensor([[0,0],[255,0]])

In [103]:
a= torch.stack([red_channel,green_channel,blue_channel])
a

tensor([[[255,   0],
         [  0, 255]],

        [[  0, 255],
         [  0, 255]],

        [[  0,   0],
         [255,   0]]])

In [104]:
a.shape

torch.Size([3, 2, 2])

In [105]:
a = torch.stack([red_channel,green_channel,blue_channel],dim=1)


In [106]:
a

tensor([[[255,   0],
         [  0, 255],
         [  0,   0]],

        [[  0, 255],
         [  0, 255],
         [255,   0]]])

In [107]:
a.shape

torch.Size([2, 3, 2])

In [108]:
a = torch.stack([red_channel,green_channel,blue_channel],dim=2)
a

tensor([[[255,   0,   0],
         [  0, 255,   0]],

        [[  0,   0, 255],
         [255, 255,   0]]])

In [109]:
a.shape

torch.Size([2, 2, 3])

In [111]:
t = torch.randn(3,2)
t

tensor([[ 0.9287, -2.1108],
        [-0.4008, -2.3513],
        [-0.6773, -0.1630]])

In [112]:
r = t.reshape(2,3)
r

tensor([[ 0.9287, -2.1108, -0.4008],
        [-2.3513, -0.6773, -0.1630]])

In [113]:
q = t.transpose(0,1)

In [114]:
q

tensor([[ 0.9287, -0.4008, -0.6773],
        [-2.1108, -2.3513, -0.1630]])

In [115]:
q[0,1]

tensor(-0.4008)

In [116]:
r[0,1]

tensor(-2.1108)

In [117]:
t = torch.randn(3,2)
t.flatten().shape

torch.Size([6])