In [14]:
import torch

In [ ]:
b = torch.tensor([[0,1],[2,3],[4,5]])
c = torch.tensor([[9,9]])

In [ ]:
d = torch.cat((b,c))
d

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [9, 9]])

In [ ]:
a = torch.tensor([3,3,3])

In [ ]:
e = torch.cat((b,a.reshape(3,1)),1)
e

tensor([[0, 1, 3],
        [2, 3, 3],
        [4, 5, 3]])

In [ ]:
f = torch.tensor([[1,2,3]])


In [ ]:
g = f.expand(4,3)
g

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [ ]:
h = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])

In [ ]:
i = h.repeat(2,3)
i

tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6, 4, 5, 6],
        [7, 8, 9, 7, 8, 9, 7, 8, 9],
        [1, 2, 3, 1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6, 4, 5, 6],
        [7, 8, 9, 7, 8, 9, 7, 8, 9]])

In [16]:
a = torch.tensor([[1,2,3],[4,5,6]])
b = torch.tensor([[3,2,1],[6,5,4]])

c = torch.add(a,b)
c

tensor([[ 4,  4,  4],
        [10, 10, 10]])

In [17]:
id(a.add_(b))

137946617283184

In [21]:
id(a)

137946617283184

In [18]:
a.add_(b)

tensor([[ 7,  6,  5],
        [16, 15, 14]])

In [19]:
a.add_(a)

tensor([[14, 12, 10],
        [32, 30, 28]])

In [20]:
a

tensor([[14, 12, 10],
        [32, 30, 28]])

In [22]:
a = torch.tensor([[1,2,3],[1,2,3]])
b = torch.tensor([1,2,3])

torch.add(a,b)

tensor([[2, 4, 6],
        [2, 4, 6]])

In [23]:
a.sub_(a)


tensor([[0, 0, 0],
        [0, 0, 0]])

In [24]:
a

tensor([[0, 0, 0],
        [0, 0, 0]])

In [25]:
a.sub(b)

tensor([[-1, -2, -3],
        [-1, -2, -3]])

In [26]:
a

tensor([[0, 0, 0],
        [0, 0, 0]])

In [28]:
a+b

tensor([[1, 2, 3],
        [1, 2, 3]])

In [33]:
a.add_(b)

tensor([[1, 2, 3],
        [1, 2, 3]])

In [34]:
a*b

tensor([[1, 4, 9],
        [1, 4, 9]])

In [35]:
torch.div(a,b)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [36]:
a.div(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [38]:
a

tensor([[1, 2, 3],
        [1, 2, 3]])

In [39]:
a.pow(b)

tensor([[ 1,  4, 27],
        [ 1,  4, 27]])

In [40]:
a.pow_(b)

tensor([[ 1,  4, 27],
        [ 1,  4, 27]])

In [41]:
a

tensor([[ 1,  4, 27],
        [ 1,  4, 27]])

In [42]:
torch.pow(a,3)

tensor([[    1,    64, 19683],
        [    1,    64, 19683]])

In [44]:
v = torch.tensor([1,2,3])
w = torch.tensor([3,2,1])

torch.eq(v,w)

tensor([False,  True, False])

In [45]:
torch.ne(v,w)

tensor([ True, False,  True])

In [46]:
torch.gt(v,w)

tensor([False, False,  True])

In [47]:
torch.ge(v,w)

tensor([False,  True,  True])

In [48]:
torch.lt(v,w)

tensor([ True, False, False])

In [49]:
torch.le(v,w)

tensor([ True,  True, False])

In [52]:
v = torch.tensor([True, False, True])
w = torch.tensor([False,False,True])

In [53]:
torch.logical_and(v,w)

tensor([False, False,  True])

In [55]:
torch.logical_or(v,w)

tensor([ True, False,  True])

In [57]:
torch.logical_xor(v,w)

tensor([ True, False, False])

In [1]:
import torch

In [2]:
a = torch.tensor([4,3], dtype=torch.float32)
l1_norm = torch.norm(a,p=1)


In [3]:
l1_norm

tensor(7.)

In [4]:
l2_norm = torch.norm(a,p=2)
l2_norm

tensor(5.)

In [5]:
c = torch.norm(a,p=float('inf'))
c

tensor(4.)

In [10]:
b = torch.tensor([1,2,3],dtype=torch.float32)
c = torch.tensor([3,4,5], dtype=torch.float32)
manhatten_distance = torch.norm(b-c,p=1)
manhatten_similarity = print(1/(1+manhatten_distance))

tensor(0.1429)
